### ISSUE TITLE
Return the original entries of inflected words

### ISSUE THREAD

**Issue by unlsycn** [miurahr/omegat-mdict#19]
**Is your feature request related to a problem? Please describe.**
When the words in the article are inflected, the dictionaries (including Collins and Longman) return a "@@@LINK=word" tag which links to the original entry but mdict plugin cannot link to it properly.

**Describe the solution you'd like**
The plugin would return the original entry to me.

![image](https://user-images.githubusercontent.com/31343548/178136030-26b166a6-6875-49cc-9c60-fd6084b9fa3f.png)

**Comment by miurahr** [comment]
Is the ``@@@LINK=`` a feature of standard specification?
If so, it should be enhanced on mdict4j project. https://codeberg.org/miurahr/mdict4j

**Comment by miurahr** [comment]
Because I don't have dictionaries you mentioned, there is no way to reproduce the issue.
@HumphreyDotSln could you tell me a test dictionary data that is open licensed and where I can download it.

**Comment by miurahr** [comment]
Issue is migrated to codeberg.org
